version: '3'
services:
  java:
    image: chatgpt-java:latest
    depends_on:
      - chatgpt-db
    command: >
      /bin/bash -c '
      while ! nc -z database 3306;
      do
        echo "wait for database";
        sleep 1;
      done;

      echo "database is ready!";
      echo "start web service here";
      '
    ports:
      - "3002:3002"
    container_name: chatgpt-java
    networks:
      - chatgpt
    environment:
      PARAMS: --spring.datasource.url=jdbc:mysql://chatgpt-db:3306/chat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai \
        --spring.datasource.username=root \
        --spring.datasource.password=123456 \
        --chat.openai_api_key=sk-xxxxxx \
        --chat.http_proxy_host= \
        --chat.http_proxy_port= \
  db:
    image: chatgpt-db:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3309:3306"
    container_name: chatgpt-db
    networks:
      - chatgpt
    environment:
      - MYSQL_ROOT_PASSWORD=123456

networks:
  chatgpt:
    driver: bridge