version: '3'
services:
  db:
    image: chatgpt-db:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3309:3306"
    container_name: chatgpt-db
    networks:
      - chatgpt
    environment:
      - MYSQL_ROOT_PASSWORD=123456

  java:
    image: chatgpt-java:latest
    restart: always
    ports:
      - "3002:3002"
    container_name: chatgpt-java
    networks:
      - chatgpt
    environment:
      PARAMS: --spring.datasource.url=jdbc:mysql://chatgpt-db:3306/chat?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai \
        --spring.datasource.username=root \
        --spring.datasource.password=123456 \
        --chat.openai_api_key=sk-xxxxxx \
        --chat.http_proxy_host= \
        --chat.http_proxy_port= \

networks:
  chatgpt:
    driver: bridge